
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jul 01 21:17:55 GMT-03:00 2010
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int FORALL = 7;
  public static final int PONTOVIRGULA = 38;
  public static final int POS = 3;
  public static final int MENORQ = 30;
  public static final int LCHAVE = 23;
  public static final int XOR = 56;
  public static final int MAIORQ = 31;
  public static final int INTEGER = 52;
  public static final int OCLISNEW = 14;
  public static final int LPAREN = 19;
  public static final int INV = 4;
  public static final int RCHAVE = 24;
  public static final int MAIORIGUAL = 33;
  public static final int PRE = 2;
  public static final int PONTO = 36;
  public static final int VIRGULA = 27;
  public static final int RPAREN = 20;
  public static final int NOT = 57;
  public static final int AND = 54;
  public static final int MENORIGUAL = 32;
  public static final int IGUAL = 28;
  public static final int OR = 55;
  public static final int MAIS = 40;
  public static final int IMPLIES = 11;
  public static final int BAG = 49;
  public static final int COLLECTION = 51;
  public static final int SELECT = 5;
  public static final int IF = 8;
  public static final int ID = 44;
  public static final int CONTEXT = 18;
  public static final int BOOLEAN = 46;
  public static final int EOF = 0;
  public static final int TRUE = 64;
  public static final int SIZE = 17;
  public static final int error = 1;
  public static final int MENOS = 41;
  public static final int EXISTS = 6;
  public static final int NUMBER = 47;
  public static final int INCLUDING = 12;
  public static final int VOID = 53;
  public static final int PONTOPONTO = 35;
  public static final int REAL = 63;
  public static final int ENDPACKAGE = 62;
  public static final int REALTYPE = 60;
  public static final int BARRA = 39;
  public static final int EXCLUDING = 13;
  public static final int ENDIF = 58;
  public static final int SHARP = 37;
  public static final int ELSE = 10;
  public static final int DIVIDIR = 43;
  public static final int PACKAGE = 61;
  public static final int INTTYPE = 59;
  public static final int THEN = 9;
  public static final int STRING = 45;
  public static final int DIFF = 29;
  public static final int SEQUENCE = 50;
  public static final int LCOLCH = 21;
  public static final int FALSE = 65;
  public static final int ATPRE = 15;
  public static final int QUATROPONTOS = 26;
  public static final int VEZES = 42;
  public static final int SET = 48;
  public static final int RESULT = 16;
  public static final int SETA = 34;
  public static final int DOISPONTOS = 25;
  public static final int RCOLCH = 22;
}

